import { type NextPage } from "next";
import Head from "next/head";

// Wrapper
import { Wrapper } from "@/components/Common/Wrapper/Wrapper";
import { Footer } from "@/components/Common/Footer/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-full bg-custom-1">
        <Wrapper className="mx-auto  h-screen max-w-5xl">
          <main>sed</main>
        </Wrapper>
        <Footer />
      </main>
    </>
  );
};

export default Home;
