import { Wrapper } from "@/components/Wrapper/Wrapper";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-custom-1">
        <Wrapper className="mx-auto max-w-5xl">sed</Wrapper>
      </main>
    </>
  );
};

export default Home;
