import { type NextPage } from "next";
import Head from "next/head";

// Auth
import { useSession } from "next-auth/react";

// Wrapper
import { Wrapper } from "@/components/Common/Wrapper/Wrapper";
import { Footer } from "@/components/Common/Footer/Footer";
import { Showcase } from "@/components/Showcase/Showcase";

const Home: NextPage = () => {
  const { status } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-full bg-custom-3">
        <Wrapper className="mx-auto  h-screen max-w-7xl">
          <Showcase />
        </Wrapper>
        {status === "unauthenticated" ? <Footer /> : null}
      </main>
    </>
  );
};

export default Home;
